void init();
void set_duty(int val);
void selecaoServos(char p);
void maqTeste();
void maqEstados();
void tela0();
void tela1();
void tela2(); 
void tela31();
void tela32(); 
void tela4();
void __interrupt(high_priority) isrH(); 
void isr_Timer0(); 
